### PR TITLE
Add flag to prevent automatically rebuilding external modules

### PR DESCRIPTION
**Pull request by petronio**

### CODE REVIEW

**Comment by sakaki-** [comment]
Looks good! Please also bump the version number (in `genup` and `genup.8`) to `1.0.22`, and then I'll merge and release this.

**Comment by petronio** [comment]
Version bumped

**Comment by sakaki-** [comment]
Merged. Thanks for contributing ^-^
I'll just push a new release and ebuild for this now...

**Comment by sakaki-** [comment]
Done.

**Pull request merged**
