### PR TITLE
Don't run buildkernel if -n/--no-kernel-upgrade passed

### PR DESCRIPTION
**Pull request by pbrkr**
Resolves issue #2.

### CODE REVIEW

**Comment by sakaki-** [comment]
Thanks for that - merged. Will release and bump the ebuild this weekend. Best, sakaki

**Comment by pbrkr** [comment]
Cheers for the quick merge! When you bump the ebuild is there any way you could make the dependency on buildkernel optional? I think a 'buildkernel' use flag which is enabled by default would probably be the best option.

**Comment by sakaki-** [comment]
Yes I was thinking that too; I currently have a sister project [genup-lite](https://github.com/sakaki-/genup-lite) (for use in embedded) that doesn't have any buildkernel stuff in there; adding a use flag to the mainline genup would allow this to be folded in, which would be better from a maintenance perspective.

**Comment by sakaki-** [comment]
Hi the ebuild is bumped now, with a `+buildkernel` USE flag; please let me know if this works at your end. Thanks, sakaki

**Comment by pbrkr** [comment]
I've tested the updated ebuild and it works as expected. Many thanks!

**Pull request merged**
